application: snippendrop
version: 1
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: snippendrop/static

- url: /favicon.ico
  static_files: snippendrop/static/logo.png
  upload: snippendrop/static/logo.png
  expiration: 1d

- url: /.*
  script: main.py
  login: required
